### ISSUE TITLE
public server soon?

### ISSUE THREAD

**Issue by qvqc** [OPolymechanos/wow#7]
this is fun!  not an issue.. tho wondering if there are plans to setup a public server to play?  a couple people have asked in chat

**Comment by OPolymechanos** [comment]
I don't have any plans to host a public server; that's more than I can manage at the moment. However, I'd love for someone to pitch this mod as an addition to a new server. 'wow' could technically be added to an existing game or server, but the ore-generation wouldn't work properly--as ore generation occurs when the map is being generated for the first time.

If I ever come across any servers using this mod, I'll be sure to create a list for folks.

**Comment by mckaygerhard** [comment]
i am interested in added this to one of my servers.. but i cannot understand what this mod/game made in detail! could you provide a more detailed readme.md file or description ? @OPolymechanos  @NathanSalapat  ?

**Comment by OPolymechanos** [comment]
@mckaygerhard Sure, I'll provide a more detailed readme file soon.

**Comment by mckaygerhard** [comment]
"soon" as so much aprox ?  ¬_¬u puff i own the two powered VenenuX subs.fusilsystem.com minetest servers the "no rulez" anarchi ones.. and want to know for what is this mod..

**Comment by OPolymechanos** [comment]
@mckaygerhard I've improved the Readme & have added crafting recipes. You may need to reconfigure the wow:pick drop-rate, however, to prevent massive WOW inflation on a server.
